// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunks_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chunkExistsByFileIdAndIndex = `-- name: ChunkExistsByFileIdAndIndex :one
SELECT EXISTS(
  SELECT 1
  FROM chunks
  WHERE file_id = $1 and chunk_index = $2
)
`

func (q *Queries) ChunkExistsByFileIdAndIndex(ctx context.Context, fileID pgtype.UUID, chunkIndex int32) (bool, error) {
	row := q.db.QueryRow(ctx, chunkExistsByFileIdAndIndex, fileID, chunkIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
