// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files_queries.sql

package sqlc

import (
	"context"
)

const getFiles = `-- name: GetFiles :one
SELECT id, share_id, encrypted_filename, encrypted_mime_type, total_size, chunk_count, chunk_size, status, created_at, expires_at, max_downloads, download_count, last_downloaded_at, deletion_token_hash, uploader_ip FROM files
`

func (q *Queries) GetFiles(ctx context.Context) (File, error) {
	row := q.db.QueryRow(ctx, getFiles)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ShareID,
		&i.EncryptedFilename,
		&i.EncryptedMimeType,
		&i.TotalSize,
		&i.ChunkCount,
		&i.ChunkSize,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.LastDownloadedAt,
		&i.DeletionTokenHash,
		&i.UploaderIp,
	)
	return i, err
}
