// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Chunk struct {
	ID            int64              `json:"id"`
	FileID        pgtype.UUID        `json:"file_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	StoragePath   string             `json:"storage_path"`
	EncrpytedSize int32              `json:"encrpyted_size"`
	ChunkHash     string             `json:"chunk_hash"`
	UploadedAt    pgtype.Timestamptz `json:"uploaded_at"`
}

type File struct {
	ID                pgtype.UUID        `json:"id"`
	ShareID           string             `json:"share_id"`
	EncryptedFilename string             `json:"encrypted_filename"`
	EncryptedMimeType string             `json:"encrypted_mime_type"`
	TotalSize         int64              `json:"total_size"`
	ChunkCount        int32              `json:"chunk_count"`
	ChunkSize         int32              `json:"chunk_size"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	MaxDownloads      pgtype.Int4        `json:"max_downloads"`
	DownloadCount     int32              `json:"download_count"`
	LastDownloadedAt  pgtype.Timestamptz `json:"last_downloaded_at"`
	DeletionTokenHash pgtype.Text        `json:"deletion_token_hash"`
	UploaderIp        *netip.Addr        `json:"uploader_ip"`
}
