// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChunkExistsByFileIdAndIndex(ctx context.Context, arg ChunkExistsByFileIdAndIndexParams) (bool, error)
	CompleteFileDownloadByShareId(ctx context.Context, shareID string) (CompleteFileDownloadByShareIdRow, error)
	CountChunksByFileId(ctx context.Context, fileID pgtype.UUID) (int64, error)
	CreateChunk(ctx context.Context, arg CreateChunkParams) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	ExpireFilesByIds(ctx context.Context, dollar_1 []pgtype.UUID) error
	FileExistsByIdAndStatus(ctx context.Context, arg FileExistsByIdAndStatusParams) (bool, error)
	GetChunkByIndexAndFileShareID(ctx context.Context, arg GetChunkByIndexAndFileShareIDParams) (GetChunkByIndexAndFileShareIDRow, error)
	GetExpiredFiles(ctx context.Context) ([]GetExpiredFilesRow, error)
	GetFileByID(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByShareID(ctx context.Context, shareID string) (File, error)
	GetFileMetadataByShareId(ctx context.Context, shareID string) (GetFileMetadataByShareIdRow, error)
	GetFileSaltByShareId(ctx context.Context, shareID string) (string, error)
	UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) (File, error)
}

var _ Querier = (*Queries)(nil)
