// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChunkExistsByFileIdAndIndex(ctx context.Context, arg ChunkExistsByFileIdAndIndexParams) (bool, error)
	CountChunksByFileId(ctx context.Context, fileID pgtype.UUID) (int64, error)
	CreateChunk(ctx context.Context, arg CreateChunkParams) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	DeleteExpiredFiles(ctx context.Context) error
	FileExistsByIdAndStatus(ctx context.Context, arg FileExistsByIdAndStatusParams) (bool, error)
	GetFileByID(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByShareID(ctx context.Context, shareID string) (File, error)
	IncrementDownloadCount(ctx context.Context, id pgtype.UUID) (File, error)
	UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) (File, error)
}

var _ Querier = (*Queries)(nil)
