// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChunkExistsByFileIdAndIndex(ctx context.Context, fileID pgtype.UUID, chunkIndex int32) (bool, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	DeleteExpiredFiles(ctx context.Context) error
	GetFileByID(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByShareID(ctx context.Context, shareID string) (File, error)
	IncrementDownloadCount(ctx context.Context, id pgtype.UUID) (File, error)
	UpdateFileStatus(ctx context.Context, iD pgtype.UUID, status string) (File, error)
}

var _ Querier = (*Queries)(nil)
